import fotoJogador from "../../imagens/lebron.png";

export const dados = [
  {
    id: 1,
    img: fotoJogador,
    nome: "LeBron James",
    idade: 38,
    time: "Los Angeles Lakers",
  },
  {
    id: 2,
    img: fotoJogador,
    nome: "Stephen Curry",
    idade: 35,
    time: "Golden State Warriors",
  },
  {
    id: 3,
    img: fotoJogador,
    nome: "Kevin Durant",
    idade: 35,
    time: "Phoenix Suns",
  },
  {
    id: 4,
    img: fotoJogador,
    nome: "Giannis Antetokounmpo",
    idade: 29,
    time: "Milwaukee Bucks",
  },
  {
    id: 5,
    img: fotoJogador,
    nome: "Nikola Jokic",
    idade: 28,
    time: "Denver Nuggets",
  },
  {
    id: 6,
    img: fotoJogador,
    nome: "Joel Embiid",
    idade: 30,
    time: "Philadelphia 76ers",
  },
  {
    id: 7,
    img: fotoJogador,
    nome: "Luka Dončić",
    idade: 24,
    time: "Dallas Mavericks",
  },
  {
    id: 8,
    img: fotoJogador,
    nome: "Jayson Tatum",
    idade: 25,
    time: "Boston Celtics",
  },
  {
    id: 9,
    img: fotoJogador,
    nome: "Damian Lillard",
    idade: 33,
    time: "Portland Trail Blazers",
  },
  {
    id: 10,
    img: fotoJogador,
    nome: "Kyrie Irving",
    idade: 31,
    time: "Dallas Mavericks",
  },
  {
    id: 11,
    img: fotoJogador,
    nome: "James Harden",
    idade: 34,
    time: "Philadelphia 76ers",
  },
  {
    id: 12,
    img: fotoJogador,
    nome: "Anthony Davis",
    idade: 30,
    time: "Los Angeles Lakers",
  },
  {
    id: 13,
    img: fotoJogador,
    nome: "Karl-Anthony Towns",
    idade: 28,
    time: "Minnesota Timberwolves",
  },
  {
    id: 14,
    img: fotoJogador,
    nome: "Donovan Mitchell",
    idade: 27,
    time: "Cleveland Cavaliers",
  },
  {
    id: 15,
    img: fotoJogador,
    nome: "DeMar DeRozan",
    idade: 33,
    time: "Chicago Bulls",
  },
  {
    id: 16,
    img: fotoJogador,
    nome: "Ja Morant",
    idade: 24,
    time: "Memphis Grizzlies",
  },
  {
    id: 17,
    img: fotoJogador,
    nome: "Zion Williamson",
    idade: 23,
    time: "New Orleans Pelicans",
  },
  {
    id: 18,
    img: fotoJogador,
    nome: "Shai Gilgeous-Alexander",
    idade: 25,
    time: "Oklahoma City Thunder",
  },
  {
    id: 19,
    img: fotoJogador,
    nome: "Devin Booker",
    idade: 26,
    time: "Phoenix Suns",
  },
  {
    id: 20,
    img: fotoJogador,
    nome: "Kawhi Leonard",
    idade: 32,
    time: "Los Angeles Clippers",
  },
];
